import { Manrope } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/common/NavigationBar";

import { ToastContainer } from "react-toastify";

const fontManrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SmoothScroll from "@/components/common/SmoothScroll";
import CustomCursor from "@/components/common/CustomCursor";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontManrope.className} h-full antialiased`}>
      <body className="bg-[#ffece3] min-h-full flex flex-col">
        <CustomCursor />
        <SmoothScroll>
          <ToastContainer />
          <NavigationBar />
          <main className="w-[85%] mx-auto">{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
