import { Manrope } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/common/NavigationBar";


const fontManrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontManrope.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
             <NavigationBar/>
        <main className="w-[80%] mx-auto">{children}</main>
      </body>
    </html>
  );
}
